import streamlit as st
from workflow import graph

# ============================================================
# Page Configuration
# ============================================================

st.set_page_config(
    page_title="AI Customer Support Automation",
    page_icon="🤖",
    layout="wide"
)

# ============================================================
# Session State
# ============================================================

if "result" not in st.session_state:
    st.session_state.result = None

if "ticket_history" not in st.session_state:
    st.session_state.ticket_history = []

# ============================================================
# Sidebar
# ============================================================

with st.sidebar:
    st.header("⚙️ Support Controls")

    st.write(
        "AI-powered customer support automation "
        "using LLM, RAG, LangGraph, and ticketing APIs."
    )

    st.divider()
    if st.button("🗑️ Clear Current Result"):
        st.session_state.result = None
        st.rerun()

    if st.button("🧹 Clear Ticket History"):
        st.session_state.ticket_history = []
        st.rerun()

# ============================================================
# Header
# ============================================================

st.title("🤖 AI Customer Support Automation")

st.write(
    "AI-powered ticket classification, knowledge retrieval, "
    "response generation, and escalation."
)

# ============================================================
# Customer Ticket Input
# ============================================================

st.subheader("📝 Customer Ticket")

ticket = st.text_area(
    "Enter the customer's support request:",
    height=180,
    placeholder=(
        "Example: I forgot my password and cannot login."
    )
)

# ============================================================
# Process Ticket Button
# ============================================================

process_ticket = st.button(
    "🚀 Process Ticket",
    type="primary"
)

# ============================================================
# Process Ticket
# ============================================================

if process_ticket:
    if not ticket.strip():
        st.warning(
            "Please enter a customer ticket."
        )
    else:
        try:
            # -----------------------------------------------
            # Run LangGraph Workflow
            # -----------------------------------------------
            with st.status(
                "Running AI support workflow...",
                expanded=True
            ) as status:
                st.write(
                    "🔍 Classifying customer ticket..."
                )
                st.write(
                    "🧠 Evaluating escalation requirement..."
                )
                st.write(
                    "📚 Retrieving relevant knowledge..."
                )
                st.write(
                    "💬 Generating AI response..."
                )
                result = graph.invoke(
                    {
                        "ticket": ticket
                    }
                )

                status.update(
                    label="✅ Workflow completed",
                    state="complete"
                )

            # -----------------------------------------------
            # Save Result in Session State
            # -----------------------------------------------
            st.session_state.result = result

            # -----------------------------------------------
            # Save Ticket History
            # -----------------------------------------------

            classification = result.get(
                "classification",
                {}
            )

            st.session_state.ticket_history.append(
                {
                    "ticket": ticket,
                    "category": classification.get(
                        "category",
                        "N/A"
                    ),
                    "priority": classification.get(
                        "priority",
                        "N/A"
                    ),
                    "escalation": result.get(
                        "escalation",
                        False
                    )
                }
            )

            # =================================================
            # Ticket Classification
            # =================================================

            st.subheader(
                "🎯 Ticket Classification"
            )

            st.caption(
                "Classification generated by the AI "
                "ticket classifier."
            )

            col1, col2, col3, col4 = st.columns(4)

            with col1:
                st.metric(
                    "Category",
                    classification.get(
                        "category",
                        "N/A"
                    )
                )

            with col2:
                st.metric(
                    "Priority",
                    classification.get(
                        "priority",
                        "N/A"
                    )
                )

            with col3:
                st.metric(
                    "Sentiment",
                    classification.get(
                        "sentiment",
                        "N/A"
                    )
                )

            with col4:
                st.metric(
                    "Escalation",
                    classification.get(
                        "escalation",
                        "N/A"
                    )
                )

            # -----------------------------------------------
            # Classification Reason
            # -----------------------------------------------
            if classification.get("reason"):
                st.write(
                    "**Classification Reason:** "
                    + classification["reason"]
                )

            # =================================================
            # AI Generated Response
            # =================================================

            st.subheader(
                "💬 AI Generated Response"
            )

            response = result.get(
                "response",
                ""
            )

            st.info(response)

            # =================================================
            # Knowledge Sources
            # =================================================

            sources = result.get(
                "sources",
                []
            )

            if sources:
                st.subheader(
                    "📚 Knowledge Sources"
                )

                for index, source in enumerate(
                    sources,
                    start=1
                ):
                    filename = source.get(
                        "source",
                        "Unknown"
                    )

                    page = source.get(
                        "page",
                        "N/A"
                    )

                    with st.expander(
                        f"📄 Source {index}: {filename}"
                    ):

                        st.write(
                            f"**Page:** {page}"
                        )

            # =================================================
            # Escalation Information
            # =================================================

            if result.get("escalation"):

                st.error(
                    "⚠️ Human intervention required"
                )

                st.write(
                    "The AI determined that this ticket "
                    "requires human support."
                )

                st.subheader(
                    "🎫 Escalation Details"
                )

                col1, col2, col3 = st.columns(3)

                with col1:
                    st.metric(
                        "Ticket ID",
                        result.get(
                            "ticket_id",
                            "N/A"
                        )
                    )

                with col2:
                    st.metric(
                        "Status",
                        result.get(
                            "ticket_status",
                            "N/A"
                        )
                    )

                with col3:
                    st.metric(
                        "Assigned To",
                        result.get(
                            "assigned_to",
                            "N/A"
                        )
                    )

            else:
                st.success(
                    "✅ Ticket successfully handled by AI."
                )

        # =====================================================
        # Error Handling
        # =====================================================
        except Exception as e:
            st.error(
                "❌ An error occurred while processing "
                "the ticket."
            )
            st.exception(e)

# ============================================================
# Ticket History
# ============================================================
if st.session_state.ticket_history:
    st.divider()
    st.subheader(
        "📋 Ticket History"
    )

    for index, item in enumerate(
        reversed(st.session_state.ticket_history),
        start=1
    ):
        escalation_status = (
            "Yes"
            if item["escalation"]
            else "No"
        )

        with st.expander(
            f"Ticket {index}: "
            f"{item['category']} - "
            f"{item['priority']}"
        ):
            st.write(
                "**Customer Ticket:**"
            )

            st.write(
                item["ticket"]
            )

            st.write(
                f"**Category:** {item['category']}"
            )

            st.write(
                f"**Priority:** {item['priority']}"
            )

            st.write(
                f"**Escalated:** {escalation_status}"
            )

